# Generated by Django 4.2.11 on 2024-03-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapCoins_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active_task_value',
        ),
    ]
