# Generated by Django 4.2.11 on 2024-03-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapCoins_API', '0002_remove_user_is_active_task_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvite',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='cancels invite'),
        ),
    ]
